#Product Index
GET http://localhost:3000/products/

###
#Product Create

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Lay's Golden Grounds",
  "price": 125,
  "description": "Bag of Lay's potato chips  made from potatoes grown in Lambeau Field soil",
  "number_in_stock": 1,
}

###
#Product Show

GET http://localhost:3000/products/8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDMxNjY2NjB9.TMp09W76JA3p4AMtzUXoKZFJafQCo207mZPAYAK2ito

###
#Product Update

PATCH http://localhost:3000/products/4
Content-Type: application/json

{
  "price": 39.99
}

###
#Product Destroy

DELETE http://localhost:3000/products/2

###