@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDQ5NTkzMjl9.Y4A2xPauV-oRRCbFk22pSBDaplUN4UIPuBhhSqetqIY

#Product Index
GET http://localhost:3000/products/

###
#Product Create

POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer {{ jwt }} 

{
  "name": "Packer QB",
  "price": 1000,
  "description": "Anything could be better than what you have",
  "number_in_stock": 1,
  "supplier_id": 1
}

###
#Product Show

GET http://localhost:3000/products/8

###
#Product Update

PATCH http://localhost:3000/products/8
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "price": 999.99
}

###
#Product Destroy

DELETE http://localhost:3000/products/15
Authorization: Bearer {{ jwt }}

###