#Users Create (Sign up)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@gmail.com",
  "password": "admin",
  "password_confirmation": "admin"
}

### 
#Sessions Create (Log in)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin"
}

###