@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDM0MjY5NzV9.9K8qm6cNOVCtKPzgKl0Jsc5A4DqULHfSep-_EqdrGhY
#nonadmin

#Suppliers Index

GET http://localhost:3000/suppliers

###
#Suppliers Create
POST http://localhost:3000/suppliers
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Sporting Goods General Store",
  "email": "super@goods.com",
  "phone_number": "262-123-4567"
}

###
#Suppliers Show
GET http://localhost:3000/suppliers/3

###
#Suppliers Update
PATCH http://localhost:3000/suppliers/4
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Spotty Sporting goods"
}

###
#Suppliers Destroy
DELETE http://localhost:3000/suppliers/4
Authorization: Bearer {{ jwt }}

###