@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDM0ODczMjF9.01_8Ee7RNkHDQGuWiH5SD7-3lRgRqzgSXYIdwv8BQO8
#yujin

#Orders Index
GET http://localhost:3000/orders/
Authorization: Bearer {{ jwt }}

###

#Orders Create
POST http://localhost:3000/orders/
Content-Type: application/json
Authorization: Bearer {{ jwt }}

###
#Orders Show

GET http://localhost:3000/orders/3
Authorization: Bearer {{ jwt }}

###